name: Update Kentucky Basketball Schedule

on:
  # Run daily at 6 AM EST (11 AM UTC)
  schedule:
    - cron: '0 11 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to main (for testing)
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-schedule.yml'
      - 'scripts/fetch_schedule.py'
      - 'scripts/fetch_rankings.py'

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Fetch AP Rankings
        run: |
          python scripts/fetch_rankings.py
      
      - name: Fetch Schedule Data
        run: |
          python scripts/fetch_schedule.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git add data/*.json
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Auto-update: Schedule and Rankings ($(date +'%Y-%m-%d %H:%M:%S'))"
          git push
      
      - name: No changes notification
        if: steps.check_changes.outputs.changes == 'false'
        run: |
          echo "Schedule and rankings are up to date. No changes committed."
