name: Update Kentucky Basketball Data

on:
  schedule:
    # Run daily at 6 AM UTC (1 AM EST)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggers
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-data.yml'
      - 'scripts/fetch_*.py'

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Fetch roster data
        run: |
          cd scripts
          python fetch_roster.py
        continue-on-error: true
      
      - name: Fetch player stats
        run: |
          cd scripts
          python fetch_playerstats.py
        continue-on-error: true
      
      - name: Fetch game logs
        run: |
          cd scripts
          python fetch_gamelog.py
        continue-on-error: true
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code data/ || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changed
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add data/*.json
          git commit -m "Auto-update: Basketball data $(date +'%Y-%m-%d %H:%M')"
          git push
      
      - name: Create summary
        if: always()
        run: |
          echo "## Data Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "data/roster.json" ]; then
            echo "✅ roster.json updated" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ roster.json failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f "data/playerstats.json" ]; then
            echo "✅ playerstats.json updated" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ playerstats.json failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f "data/gamelog.json" ]; then
            echo "✅ gamelog.json updated" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ gamelog.json failed" >> $GITHUB_STEP_SUMMARY
          fi
